Adds Validators for IAM
adobe/griffon-validation-plugins pull request #20
Opened 2022-02-01 17:50 UTC by dsoffiantini

## Description

Adds a set of griffon validators for In App Messaging events and configuration

## Motivation and Context

With the launch of IAM, we want to provide users feedback on any errors they may encounter with their app.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-02-02 16:14 UTC, dgrossen commented on plugins/aep-iam-configuration/index.ts
> +        errors: configEvents.map((event) => event.uuid),
`errors` is only supported for backwards compatibility and should be replaced with `events`

2022-02-02 16:14 UTC, dgrossen commented on plugins/aep-iam-configuration/index.ts
> +        status: 'invalid'
I don't think this is a valid enumerated value for `status`

2022-02-02 16:15 UTC, dgrossen commented on plugins/aep-iam-configuration/index.ts
> +      };
`result` enumerated value is required for validators

https://github.com/adobe/griffon-validation-plugins/wiki/Writing-a-Validation-Function#returning-validation-results

2022-02-02 16:16 UTC, dgrossen requested changes
Looks like in this PR and in other validators we aren't returning the expected results object. These validators will fail when run in the validation manager (bootes)

https://github.com/adobe/griffon-validation-plugins/wiki/Writing-a-Validation-Function#returning-validation-results

2022-02-02 16:23 UTC, dgrossen commented
The following validators are returning an incompatible results object:

https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-messaging-config/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-messaging-installed/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-messaging-push-on-platform/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-messaging-pushid/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-optimize-peer-dependencies/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/aep-optimize-prerequisites/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/edge-config/index.ts
https://github.com/adobe/griffon-validation-plugins/blob/master/plugins/edge-installed/index.ts

2022-02-02 16:39 UTC, amadt commented
@dgrossen: Sounds like we should flesh out the `ValidationPluginResult` type?

2022-02-02 16:46 UTC, dgrossen commented
@amadt I believe we already did back in September. The manager only accepts `loading`, `invalid auth`, and `prerequisite missing`. `invalid` and `valid` are superfluous to `not matched` and `matched`

https://git.corp.adobe.com/dms-mobile/bootes/blob/master/packages/validation-plugin-manager/src/sagas/validate.events.saga.js#L46

2022-02-02 18:22 UTC, dsoffiantini commented
@dgrossen Updated out typescript definition to match what the platform expects. I fixed up the plugins minus the optimize ones, which are fixed on my other pr :)

2022-02-04 21:02 UTC, dgrossen commented on plugins/aep-iam-request/index.ts
> +        result: 'valid',
invalid result enum

`matched` | `not matched` | `unknown`

2022-02-04 21:02 UTC, dgrossen commented on plugins/aep-iam-response-events/index.ts
> +        result: 'valid'
invalid result enum

2022-02-04 21:03 UTC, dgrossen requested changes
a few invalid result enums

2022-02-09 18:55 UTC, dsoffiantini commented on plugins/aep-iam-response-events/index.ts
> +        result: 'valid'
@dgrossen Think I got them all :)

2022-02-09 18:58 UTC, dgrossen approved these changes

2022-02-16 19:31 UTC, merged